<a href="https://colab.research.google.com/github/punchika-f/data-bootcamp/blob/main/Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Python Programming 101
1. variable
2. data type
3. data structure
4. control flow
5. function

In [ ]:
# variable
1+1

2

In [ ]:
10%4

2

In [ ]:
# variables

x = 100
y = 200
print(x+y)

300


In [ ]:
#naming variable -> snake case
my_name = "Fai"
my_age = 26
economics_gpa = 3.55
netflix = True

In [ ]:
print(my_name, economics_gpa, netflix)

Fai 3.55 True


In [ ]:
print("Hello!", "My name is", "Faii")

Hello! My name is Faii


In [ ]:
## create multiple variable
x, y, z = 100, 200, 300
print(x, y, z)

100 200 300


In [ ]:
## replace value
my_name = "faii"
my_name = "Faii"
print(my_name)

Faii


In [ ]:
## remove variable
del my_name

In [ ]:
## convert data type
bool(0)

False

In [ ]:
str(300)

'300'

In [ ]:
int(555)

555

In [ ]:
float("3.41")

3.41

In [ ]:
input("What's your name : ")

What's your name : faii


'faii'

In [ ]:
input("What's your name : ")

What's your name : โฟรร


'โฟรร'

In [ ]:
age = int(input("What's your age : "))

What's your age : 26


In [ ]:
print(age,type(age))

26 <class 'int'>


In [ ]:
500+1000

1500

In [ ]:
"500" + "1000"

'5001000'

In [ ]:
int("500")+int("1000")

1500

In [ ]:
my_name = "Fai"
my_age = 26

text = f"Hi! myname is {my_name} and I'm {my_age}"

In [ ]:
print(text)

Hi! myname is Fai and I'm 26


In [ ]:
## function
## def ?
def double(x) :
  return x*2

In [ ]:
double(6)

12

In [ ]:
def greeting(name, food = "sushi") :
  text = f"{name} like to eat {food}"
  return text

In [ ]:
greeting("faii")

'faii like to eat sushi'

In [ ]:
greeting("faii", "cake")

'faii like to eat cake'

In [ ]:
def greeting2(x) :
  return (x**2, x+2, x+6)

In [ ]:
x, y, _ = greeting2(5)
print(x, y)

25 7


In [ ]:
def f1() :
  print("Hi!")

def f2() :
  print("Hello!")

def f3() :
  print("Bye!")

def f4() :
     f1() # load data
     f2() # clean data
     f3() # prep data
     print("done!!")

In [ ]:
f4()

Hi!
Hello!
Bye!
done!!


In [ ]:
def grade(score) :
  if score >= 90 :
    return "Passed"
  else :
    return "Please retake exam"

In [ ]:
grade(70)

'Please retake exam'

In [ ]:
def grade_adv(score) :
  if score >= 90 :
    return "A"
  elif score >= 80 :
    return "B"
  elif score >= 70 :
    return "C"
  elif score >= 60 :
    return "D"
  else :
    return "F"

In [ ]:
grade_adv(77)

'C'

In [ ]:
def testing() :
  if (1+1 == 2 and 2*2 == 5) :
    print("correct")
  else :
    print("wrong")

In [ ]:
testing()

wrong


In [ ]:
my_shopping = ["egg", "milk", "bread"]

## index starts at zero
print(my_shopping[0])
print(my_shopping[1])
print(my_shopping[2])

## check number of items
print(len(my_shopping))

egg
milk
bread
3


In [ ]:
my_shopping[0] = 'orange'
my_shopping[1] = 'milk 2 gallons'

In [ ]:
my_shopping

['orange', 'milk 2 gallons', 'bread']

In [ ]:
my_shopping.append("honey")
my_shopping

['orange', 'milk 2 gallons', 'bread', 'honey']

In [ ]:
my_shopping.pop()
my_shopping

['orange', 'milk 2 gallons', 'bread']

In [ ]:
my_shopping.remove("bread")
my_shopping

['orange', 'milk 2 gallons']

In [ ]:
my_shopping.insert(0, "bread")
my_shopping

['bread', 'orange', 'milk 2 gallons']

In [ ]:
my_shopping.sort(reverse = True)
my_shopping

['orange', 'milk 2 gallons', 'bread']

In [ ]:
full_list = ['egg', 'milk'] + ['Thai', 'Japan']
print(full_list)

['egg', 'milk', 'Thai', 'Japan']


In [ ]:
for item in full_list :
  print(item)

egg
milk
Thai
Japan


In [ ]:
fruits = ['banana', 'apple', 'orange']

for fruit in fruits :
  if fruit == "banana" :
    print("delicious")
  else :
    print("not delicious")

delicious
not delicious
not delicious


In [ ]:
fruits = ['banana', 'apple', 'orange']

for fruit in fruits :
  print(fruit.upper())

BANANA
APPLE
ORANGE


In [ ]:
fruits = ['banana', 'apple', 'orange']

for fruit in fruits :
  print(fruit.title())

Banana
Apple
Orange


In [ ]:
text = "a duck walks into a bar"
text = text.replace("duck", "lion")
text

'a lion walks into a bar'

In [ ]:
friends = ['Toy', 'Faii', 'Tang', 'Mook']
friends[0] = 'Song'
friends

['Song', 'Faii', 'Tang', 'Mook']

In [ ]:
my_name = "Tunchika"
my_name = "P" + my_name[1: ]
my_name

'Punchika'

In [ ]:
for i in range(5) :
  print(i)

0
1
2
3
4


In [ ]:
count = 0

while(count < 5) :
  print("hi!")
  count += 1

hi!
hi!
hi!
hi!
hi!


In [ ]:
while True :
  user_input = input("what do you want to eat ? ")
  print(user_input)
  if user_input == "I'm full" :
    print("bye!")
    break

what do you want to eat ? banana
banana
what do you want to eat ? I'm full
I'm full
bye!


In [ ]:
alive = True
while alive :
  print("Live Learn Repeat!")
  ui = input("Do you want to stop ? ")
  if ui == "yes" :
    alive = False

Live Learn Repeat!
Do you want to stop ? no
Live Learn Repeat!
Do you want to stop ? yes


In [ ]:
laptops = ['lenovo', 'dell', 'apple']

result = [] #empty list

for laptop in laptops :
  change = laptop.upper()
  result.append(change)

result

['LENOVO', 'DELL', 'APPLE']

In [ ]:
laptops = ['lenovo', 'dell', 'apple']

laptops_upper = [laptop.upper() for laptop in laptops]
laptops_upper

['LENOVO', 'DELL', 'APPLE']

In [ ]:
x = (1,2,3)
print(x, type(x))

(1, 2, 3) <class 'tuple'>


In [ ]:
fruits = {"orange", "lemon", "lemon", "lemon", "apple", "apple"}
fruits

{'apple', 'lemon', 'orange'}

In [ ]:
a = {"apple", "banana", "cherry"}
b = {"google", "microsoft", "apple"}

a & b

{'apple'}

In [ ]:
a | b

{'apple', 'banana', 'cherry', 'google', 'microsoft'}

In [ ]:
a-b

{'banana', 'cherry'}

In [ ]:
user = {
    "name" : "Faii",
    "age" : 26,
    "location" : "Thailand",
    "steaming" : {"nf" : True ,
                        "amaz" : False},
    "fav_movies" : ["Spider man", "Barbie"]
}
user

{'name': 'Faii',
 'age': 26,
 'location': 'Thailand',
 'steaming': {'nf': True, 'amaz': False},
 'fav_movies': ['Spider man', 'Barbie']}

In [ ]:
user["age"] = 50
user["name"] = "John Wick"
user

{'name': 'John Wick',
 'age': 50,
 'location': 'Thailand',
 'steaming': {'nf': True, 'amaz': False},
 'fav_movies': ['Spider man', 'Barbie']}

In [ ]:
user["dog_name"] = "Juju"
user

{'name': 'John Wick',
 'age': 50,
 'location': 'Thailand',
 'steaming': {'nf': True, 'amaz': False},
 'fav_movies': ['Spider man', 'Barbie'],
 'dog_name': 'Juju'}

In [ ]:
del user["dog_name"]
user

{'name': 'John Wick',
 'age': 50,
 'location': 'Thailand',
 'steaming': {'nf': True, 'amaz': False},
 'fav_movies': ['Spider man', 'Barbie']}

In [ ]:
user["fav_movies"] = "Avengers","Barbie","Conan"
user

{'name': 'John Wick',
 'age': 50,
 'location': 'Thailand',
 'steaming': {'nf': True, 'amaz': False},
 'fav_movies': ('Avengers', 'Barbie', 'Conan')}

In [ ]:
user["fav_movies"][0:2]

('Avengers', 'Barbie')

In [ ]:
from math import pi
pi

3.141592653589793

In [ ]:
from math import pi, log, exp
exp(5)

148.4131591025766

In [ ]:
from random import choice

In [ ]:
choice(["ค้อน", "กรรไกร", "กระดาษ"])

'กระดาษ'

#Essential Python for DA
- OOP
- Pandas / Numpy
- Request

In [ ]:
# OOP
# Object Oriented Programming

In [ ]:
class Human:
  ## initializtion (create)
  def __init__(self, name, age, country) :
    self.name = name
    self.age = age
    self.country = country

  ## string method
  def __str__(self) :
    return "I am Human!"

  ## your own method
  def greeting(self) :
    print(f"Hi! my name is {self.name}")

  ## age + 1
  def get_older(self, years) :
    self.age += years
    print(f"Age increase by {years}")

In [ ]:
human1 = Human("Fai", 26, "Thailand")
human2 = Human("Lisa", 27, "Japan")
human3 = Human("Toy", 37, "India")

In [ ]:
print(human1.name, human1.age, human1.country)

Fai 26 Thailand


In [ ]:
print(human1)

I am Human!


In [ ]:
human3.greeting()


Hi! my name is Toy


In [ ]:
human2.get_older(5)

Age increase by 5


In [ ]:
human2.age

32

In [ ]:
class ATM :
  def __init__(self, name, balance, bank) :
    self.name = name
    self.balance = balance
    self.bank = bank

  def deposit(self, amt) :
    self.balance += amt
    print(f"Deposit {amt} successfully")

  def check_balance(self) :
    print(f"Your current balance is {self.balance}")

  def withdraw(self, amt) :
    if self.balance >= amt :
      self.balance -= amt
      print(f"Withdraw {amt} successfully")
    else :
      print("Insufficient balance")

  def transfer(self, amt) :
    if self.balance >= amt :
      self.balance -= amt
      input ("Please provide account pin : ")
      print(f"Transfer {amt} successfully")
    else :
      print("Insufficient balance")

  def update_book(self) :
    input("please provide your pin : ")
    print("update book successfully")

In [ ]:
Faii = ATM("Faii", 1000, "KBank")
Mook = ATM("Mook", 2000, "SCB")

In [ ]:
Faii.deposit(500)

Deposit 500 successfully


In [ ]:
print(Faii.balance)

1500


In [ ]:
Faii.check_balance()

Your current balance is 1500


In [ ]:
Faii.withdraw(500)

Please provide account number : 3587
Withdraw 500 successfully


In [ ]:
Faii.withdraw(10000)

Insufficient balance


In [ ]:
Faii.transfer(500)

Please provide account pin : 4564
Transfer 500 successfully


In [ ]:
Faii.check_balance()

Your current balance is 500


In [ ]:
Faii.update_book()

please provide your pin : 45456
update book successfully


#API 101 in Python

In [ ]:
## standard module (library)
import requests

In [ ]:
url = "https://www.swapi.tech/api/people/1"

resp = requests.get(url)
resp

<Response [200]>

In [ ]:
resp.json()

{'message': 'ok',
 'result': {'properties': {'created': '2025-04-29T17:52:28.143Z',
   'edited': '2025-04-29T17:52:28.143Z',
   'name': 'Luke Skywalker',
   'gender': 'male',
   'skin_color': 'fair',
   'hair_color': 'blond',
   'height': '172',
   'eye_color': 'blue',
   'mass': '77',
   'homeworld': 'https://www.swapi.tech/api/planets/1',
   'birth_year': '19BBY',
   'url': 'https://www.swapi.tech/api/people/1'},
  '_id': '5f63a36eee9fd7000499be42',
  'description': 'A person within the Star Wars universe',
  'uid': '1',
  '__v': 2},
 'apiVersion': '1.0',
 'timestamp': '2025-04-30T09:03:29.043Z',
 'support': {'contact': 'admin@swapi.tech',
  'donate': 'https://www.paypal.com/donate/?business=2HGAUVTWGR5T2&no_recurring=0&item_name=Support+Swapi+and+keep+the+galaxy%27s+data+free%21+Your+donation+fuels+open-source+innovation+and+helps+us+grow.+Thank+you%21+%F0%9F%9A%80&currency_code=USD',
  'partnerDiscounts': {'saberMasters': {'link': 'https://www.swapi.tech/partner-discount/sabermaste

In [ ]:
## loop api
import requests
import time

names = []
heights = []
masses = []

for i in range(5) :
  url = f"https://www.swapi.tech/api/people/{i+1}"
  resp = requests.get(url)
  name = resp.json()['result']['properties']['name']
  height = resp.json()['result']['properties']['height']
  mass = resp.json()['result']['properties']['mass']
  names.append(name)
  heights.append(height)
  masses.append(mass)
  print(name)
  time.sleep(1)

Luke Skywalker
C-3PO
R2-D2
Darth Vader
Leia Organa


In [ ]:
import pandas as pd
df = pd.DataFrame({"name" : names,
                              "height" : heights,
                              "mass" : masses})
df

name height mass
0  Luke Skywalker    172   77
1           C-3PO    167   75
2           R2-D2     96   32
3     Darth Vader    202  136
4     Leia Organa    150   49

# Pandas , Numpy

The most common for DA

Numpy : numerical python (fast computation)

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
list_a = [1,2,3,4,5,6,7,8,9,10]
sum(list_a)

55

In [ ]:
def sum_seq(lst) :
  result = (lst[0] + lst[-1]) * lst[-1] / 2
  return result

In [ ]:
sum_seq(list_a)

55.0

In [ ]:
import numpy as np

list_a = [1,2,3,4,5]
np_a = np.array(list_a)
np_a

array([1, 2, 3, 4, 5])

In [ ]:
print(
    np.sum(np_a),
    np.mean(np_a),
    np.std(np_a),
    np.median(np_a),
    np.min(np_a),
    np.max(np_a),
    np.var(np_a)
)

15 3.0 1.4142135623730951 3.0 1 5 2.0


In [ ]:
np_a.mean()

np.float64(3.0)

In [ ]:
## 2D array
mat_a = np.array([
    [1,2],
    [3,4]
])
mat_a

array([[1, 2],
       [3, 4]])

In [ ]:
mat_a + 2

array([[3, 4],
       [5, 6]])

In [ ]:
mat_a[0]

array([1, 2])

In [ ]:
mat_a[0,1]

np.int64(2)

In [ ]:
# dot matrix
# matrix  multiplication
mat_a = np.array([
    [1,2],
    [3,4]
])
mat_b = np.array([
    [3,3],
    [5,1]
])
np.dot(mat_a, mat_b)

array([[13,  5],
       [29, 13]])

In [ ]:
txt = "Hello Mickey!"
x = txt.casefold()
print(x)

hello mickey!


In [ ]:
 fruits = ['apple', 'banana', 'cherry']
 fruits.pop(2)
 print(fruits)

['apple', 'banana']


In [ ]:
print("Hello", "how are you?", sep="---")

Hello---how are you?


In [ ]:
x = "5"
y = "5"
print(x + y)

55


In [ ]:
txt = "hello, and welcome to my world."
x = txt.title()
print (x)

Hello, And Welcome To My World.


In [ ]:
print("Python","is","awesome")

Python is awesome


In [ ]:

x = int(5)
x

5

In [ ]:
x = "Hello"[0]
x

'H'

In [ ]:
txt = "hello, and welcome to my world."
x = txt.capitalize()
print (x)

Hello, and welcome to my world.


# Essential Python for DA part 2

## special topics in python

In [ ]:
## type hint
name : str = "Faii"
age : int = 26
gpa : float = 3.27
netflix : bool = True

In [ ]:
type(age), type(gpa), type(name), type(netflix)

(int, float, str, bool)

In [ ]:
#type hint in function
def add(a : int, b : int) -> int :
  return a + b

add(5,7)

12

In [ ]:
from typing import List

In [ ]:
friends : List[str] = ["Faii", "Toy", "Mook"]

for f in friends :
  print(f"Hi! my name is {f}")

Hi! my name is Faii
Hi! my name is Toy
Hi! my name is Mook


In [ ]:
add_lambda = lambda a,b : a+b

add_lambda(1,2)

3

In [ ]:
result = []
original = [1,2,3,4,5]

for number in original :
  result.append(number * 2)

result

[2, 4, 6, 8, 10]

In [ ]:
original = [1,2,3,4,5]

[number * 2 for number in original]

[2, 4, 6, 8, 10]

In [ ]:
scores = [55, 45, 80, 87, 99]

["passed" if score >= 80 else "failed"
  for score in scores]

['failed', 'failed', 'passed', 'passed', 'passed']

In [ ]:
try :
  result = 1/0
  print(result)
except :
  print("cannot divide by zero")

cannot divide by zero


In [ ]:
eiei = 5

try:
  print(eieirrrrrrrrrrrrrr)
except NameError:
  print("pks recheck your data name")
except ZeroDivisionError:
  print("cannot divide by zero")
except ValueError:
  print("something went wrong with value")
else:
  print("the value is printed")
finally:
  print("ended")

pks recheck your data name
ended


In [ ]:
!cat hotel.csv

id,hotel,price,location
1,A,1000,NW
2,B,2000,CNX
3,C,3500,BKK
4,D,4400,BKK


In [ ]:
import csv
file = open("hotel.csv", "r")

In [ ]:
data = csv.reader(file)

for row in data :
  print(row)

['id', 'hotel', 'price', 'location']
['1', 'A', '1000', 'NW']
['2', 'B', '2000', 'CNX']
['3', 'C', '3500', 'BKK']
['4', 'D', '4400', 'BKK']


In [ ]:
with open("hotel.csv", "r") as file :
  data = csv.reader(file)
  for row in data :
    print(row)

['id', 'hotel', 'price', 'location']
['1', 'A', '1000', 'NW']
['2', 'B', '2000', 'CNX']
['3', 'C', '3500', 'BKK']
['4', 'D', '4400', 'BKK']


In [ ]:
import csv
header = ["id", "student_name", "age"]
body = [
    [1, "Faii", 26],
    [2, "Mook", 27],
    [3, "Tang", 25]
]

with open("new_file.csv", "w") as file:
  writer = csv.writer(file)
  writer.writerow(header)
  writer.writerows(body)

!cat new_file.csv

id,student_name,age
1,Faii,26
2,Mook,27
3,Tang,25


In [ ]:
try :
  with open("new_file.csv", "r") as file :
    data = csv.reader(file)
    for row in data :
      print(row)
except FileNotFoundError :
  print("file not found")

['id', 'student_name', 'age']
['1', 'Faii', '26']
['2', 'Mook', '27']
['3', 'Tang', '25']


In [ ]:
x = [1, 2, 3]
y = x
y[1] = 10
print(x)

[1, 10, 3]
